title: dlarns999
description: GitHub Pages + Jekyll 블로그
locale: ko-KR

remote_theme: "mmistakes/minimal-mistakes@4.2.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# 홈 페이지 섹션 한글화
home:
  recent_posts:
    title: "최근 글"
